version: '3.7'

services:
  odoo_db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - odoo-db:/var/lib/postgresql/data
  odoo:
    container_name: odoo
#    image: odoo11-18.04
    build: .
    ports:
      - "80:8069"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      ODOO_RC: /opt/odoo/odoo.conf
    volumes:
#      - ./extra_addons:/opt/odoo/extra_addons
      - ./odoo.conf:/opt/odoo/odoo.conf
      - ./odoo:/var/lib/odoo
    restart: always
volumes:
    odoo:
    odoo-db: